name: Windows CI

on:
  push:
    branches: [ master ]
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:

#  windows_5_15_2_gcc_build:
#
#    runs-on: windows-latest
#
#    steps:
#    - uses: actions/checkout@v3
#    # see: https://github.com/jurplel/install-qt-action
#    - uses: jurplel/install-qt-action@v3
#      with:
#        # Directory to install Qt
#        dir: # optional
#        # Version of Qt to install
#        version: '5.15.2'
#        # Host platform
#        host: # optional
#        # Target platform for build
#        target: 'desktop'
#        # Architecture for Windows/Android
#        arch: 'win64_mingw81'
#        # Whether or not to install Qt dependencies on Linux
#        install-deps: 'true'
#        # Additional Qt modules to install
#        modules: ''
#        # Force a Qt mirror in case the default is not working
#        #mirror: # optional
#        # Whether or not to actually download Qt
#        cached: # optional, default is false
#        # Version of aqtinstall to use in case of issues
#        aqtversion: # optional, default is ==0.8
#        # Version of py7zr to use in case of issues
#        py7zrversion: # optional, default is ==0.6
#        # Any extra arguments to append to the back
#        #mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
#        #setup-python: 'true'
#        #tools-only: 'false'
#        #aqtversion: '==0.10.0'
#        #py7zrversion: '==0.11.0'
#        #extra: '--external 7z'
#        # REMARK: see: https://download.qt.io/online/qtsdkrepository/ for new versions of ifw and for (version) real name
#        tools: 'tools_ifw,4.4.1-0-202206210642,qt.tools.ifw.44'
#    - name: Install Qt and compile
#      run: |
#        dir
#        d:
#        dir
#        gcc -v
#        qmake -r QuickScintilla.pro
#        dir
#        mingw32-make -j 4
#        dir
#        dir scintilla
#        dir QuickScintillaDemoApp
#        dir scintilla\bin-x86

  windows_5_15_2_msc_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: jurplel/install-qt-action@v3
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '5.15.2'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_msvc2019_64'
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: ''
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
        tools: 'tools_ifw'
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
    - name: Install Qt and compile
      run: |
        cd 
        dir
        d:
        dir
        cl
        qmake -r QuickScintilla.pro
        dir
        nmake
        dir
        dir scintilla
        dir QuickScintillaDemoApp
        dir scintilla\bin-x86


#  windows_6_3_1_gcc_build:
#
#    runs-on: windows-latest
#
#    steps:
#    - uses: actions/checkout@v3
#    # see: https://github.com/jurplel/install-qt-action
#    - uses: jurplel/install-qt-action@v3
#      with:
#        # Directory to install Qt
#        dir: # optional
#        # Version of Qt to install
#        version: '6.3.1'
#        # Host platform
#        host: # optional
#        # Target platform for build
#        target: 'desktop'
#        # Architecture for Windows/Android
#        arch: 'win64_mingw'
#        # Whether or not to install Qt dependencies on Linux
#        install-deps: 'true'
#        # Additional Qt modules to install
#        modules: 'qt5compat'
#        # Force a Qt mirror in case the default is not working
#        #mirror: # optional
#        # Whether or not to actually download Qt
#        cached: # optional, default is false
#        # Version of aqtinstall to use in case of issues
#        aqtversion: # optional, default is ==0.8
#        # Version of py7zr to use in case of issues
#        py7zrversion: # optional, default is ==0.6
#        # Any extra arguments to append to the back
#        #mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
#        #setup-python: 'true'
#        #tools-only: 'false'
#        #aqtversion: '==0.10.0'
#        #py7zrversion: '==0.11.0'
#        #extra: '--external 7z'
#        # REMARK: see: https://download.qt.io/online/qtsdkrepository/ for new versions of ifw and for (version) real name
#        tools: 'tools_ifw,4.4.1-0-202206210642,qt.tools.ifw.44'
#    - name: Install Qt and compile
#      run: |
#        dir
#        d:
#        dir
#        gcc -v
#        qmake -r QuickScintilla.pro
#        dir
#        mingw32-make -j 4
#        dir
#        dir scintilla
#        dir QuickScintillaDemoApp
#        dir scintilla\bin-x86
        
  windows_6_3_2_msc_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: jurplel/install-qt-action@v3
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '6.3.2'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_msvc2019_64'
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qt5compat'
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
        #mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        #setup-python: 'true'
        #tools-only: 'false'
        #aqtversion: '==0.10.0'
        #py7zrversion: '==0.11.0'
        #extra: '--external 7z'
        tools: 'tools_ifw'
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
    - name: Install Qt and compile
      run: |
        cd 
        dir
        d:
        dir
        cl
        qmake -r QuickScintilla.pro
        dir
        nmake
        dir
        dir scintilla
        dir QuickScintillaDemoApp
        dir scintilla\bin-x86

  windows_6_4_1_msc_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: jurplel/install-qt-action@v3
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '6.4.1'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_msvc2019_64'
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qt5compat'
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
        #mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        #setup-python: 'true'
        #tools-only: 'false'
        #aqtversion: '==0.10.0'
        #py7zrversion: '==0.11.0'
        #extra: '--external 7z'
        tools: 'tools_ifw'
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
    - name: Install Qt and compile
      run: |
        cd 
        dir
        d:
        dir
        cl
        qmake -r QuickScintilla.pro
        dir
        nmake
        dir
        dir scintilla
        dir QuickScintillaDemoApp
        dir scintilla\bin-x86
